import type { Root, Element, Node } from 'hast'
import type { Plugin } from 'unified'
import fs from 'node:fs'
import path from 'node:path'

const MAX_WIDTH = 460

/**
 * Image dimensions come from a manifest built by
 * scripts/build-image-dimensions.mjs, NOT from reading the image itself.
 *
 * This used to do `fs.readFileSync(path.join(process.cwd(), 'public', src))`.
 * `src` is only known at request time, so @vercel/nft — which decides what
 * ships inside a serverless function — could not resolve it, and
 * conservatively traced the ENTIRE 3.3GB public/ tree into the bundle of every
 * dynamic route reaching this plugin. Both article routes do. That alone put
 * the repo at ~7.3GB of build output against an 8GB build machine, and one
 * more such route was enough to fail the deploy with `ENOSPC: no space left on
 * device` — an error raised while collecting build traces, nowhere near the
 * code responsible.
 *
 * The path below is a literal, so nft resolves it to exactly one 2MB file.
 * KEEP IT LITERAL. Assembling it from a runtime value brings the 3.3GB back,
 * and the failure will not look related to the change that caused it.
 */
const MANIFEST_PATH = path.join(process.cwd(), 'data', 'image-dimensions.json')

let manifest: Record<string, [number, number]> | null = null

function dimensionManifest(): Record<string, [number, number]> {
  if (manifest) return manifest
  try {
    manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8')) as Record<string, [number, number]>
  } catch {
    // Generated by `npm run build`, so absence means someone ran `next build`
    // or `next dev` without it. Say so: the silent version of this is portrait
    // images quietly losing their treatment site-wide, which nobody notices.
    console.warn(
      '[rehype-portrait-images] data/image-dimensions.json is missing — lone portrait ' +
      'images will not be centred or capped. Run `node scripts/build-image-dimensions.mjs`.'
    )
    manifest = {}
  }
  return manifest ?? {}
}

/**
 * Rehype plugin that gives lone portrait/square images a consistent
 * treatment: centred, capped at MAX_WIDTH (never upscaled past the file's
 * own width), caption centred beneath. Landscape images are left untouched
 * so they keep filling the body measure.
 *
 * Must run after rehype-image-grid — that plugin claims runs of 2+
 * consecutive images into galleries first, so any `<p><img></p>` still
 * standing here is a genuine lone image. The one exception is an odd
 * leftover from a gallery run (rehype-image-grid tags those images with an
 * `object-cover` class even when it emits them as a plain paragraph) —
 * those are left alone too, since they belong to a run, not a lone image.
 */
const rehypePortraitImages: Plugin<[], Root> = () => {
  return (tree: Root) => {
    const children = tree.children as Node[]
    let i = 0

    while (i < children.length) {
      if (!isImageOnlyParagraph(children[i])) {
        i++
        continue
      }

      const para = children[i] as Element
      const img = para.children.find(
        (c): c is Element => c.type === 'element' && c.tagName === 'img'
      )!

      const existingClass = img.properties?.class
      const belongsToGalleryRun =
        typeof existingClass === 'string' && existingClass.includes('object-cover')

      let next = i + 1
      while (next < children.length && isWhitespaceText(children[next])) next++
      const hasCaption = next < children.length && isCaption(children[next])
      const caption = hasCaption ? (children[next] as Element) : undefined
      const spliceEnd = hasCaption ? next + 1 : i + 1

      if (belongsToGalleryRun) {
        i = spliceEnd
        continue
      }

      const dims = readImageDimensions(String(img.properties?.src ?? ''))

      // Landscape, or dimensions unreadable — leave untouched.
      if (!dims || dims.width > dims.height) {
        i = spliceEnd
        continue
      }

      const cappedWidth = Math.min(MAX_WIDTH, dims.width)
      img.properties = {
        ...img.properties,
        width: dims.width,
        height: dims.height,
        class: 'w-full h-auto rounded',
      }

      const figureChildren: Element[] = [img]
      if (caption) {
        figureChildren.push({
          type: 'element',
          tagName: 'figcaption',
          properties: { class: 'text-center text-xs mt-2' },
          children: caption.children,
        })
      }

      const figure: Element = {
        type: 'element',
        tagName: 'figure',
        properties: { class: 'not-prose mx-auto my-8', style: `max-width:${cappedWidth}px` },
        children: figureChildren,
      }

      children.splice(i, spliceEnd - i, figure)
      i += 1
    }
  }
}

function readImageDimensions(src: string): { width: number; height: number } | null {
  if (!src || !src.startsWith('/')) return null
  // Looked up verbatim, exactly as the old filesystem read resolved it — the
  // manifest is keyed by the un-decoded path, so a src carrying %20 misses
  // here just as it failed to open before. Same behaviour, deliberately.
  const hit = dimensionManifest()[src]
  return hit ? { width: hit[0], height: hit[1] } : null
}

function isCaption(node: Node): boolean {
  if (node.type !== 'element') return false
  return (node as Element).tagName === 'h6'
}

function isWhitespaceText(node: Node): boolean {
  if (node.type !== 'text') return false
  return (node as unknown as { value: string }).value.trim() === ''
}

function isImageOnlyParagraph(node: Node): boolean {
  if (node.type !== 'element') return false
  const el = node as Element
  if (el.tagName !== 'p') return false

  const meaningful = el.children.filter(
    (c) => !(c.type === 'text' && (c as { value: string }).value.trim() === '')
  )

  return (
    meaningful.length === 1 &&
    meaningful[0].type === 'element' &&
    (meaningful[0] as Element).tagName === 'img'
  )
}

export default rehypePortraitImages
